# Midi
from __future__ import absolute_import, print_function, unicode_literals
from novation import sysex
MODEL_ID_BYTE_SUFFIX = (1, 0, 1)
FLK_25_ID_BYTE = 60
FLK_37_ID_BYTE = 61
FLK_49_ID_BYTE = 62
FLK_61_ID_BYTE = 63
FLK_88_ID_BYTE = 64
MODEL_ID_BYTES = (
 FLK_25_ID_BYTE,
 FLK_37_ID_BYTE,
 FLK_49_ID_BYTE,
 FLK_61_ID_BYTE,
 FLK_88_ID_BYTE)
SMALL_MODEL_ID_BYTES = (
 FLK_25_ID_BYTE,
 FLK_37_ID_BYTE) 
INCONTROL_ONLINE_VALUE = 127
PAD_DRUM_LAYOUT = 1
PAD_SESSION_LAYOUT = 2
VOLUME_LAYOUT = 1
PAN_LAYOUT = 3
DISPLAY_HEADER = sysex.STD_MSG_HEADER + (15, )
DISPLAY_HEADER_88_KEY = sysex.STD_MSG_HEADER + (18, )
NOTIFICATION_DISPLAY_COMMAND_BYTES = ((4, 0), (4, 1))
PARAMETER_NAME_DISPLAY_COMMAND_BYTE = 7
PARAMETER_VALUE_DISPLAY_COMMAND_BYTE = 8
POT_PARAMETER_DISPLAY_START_INDEX = 56
FADER_PARAMETER_DISPLAY_START_INDEX = 80
MASTER_PARAMETER_DISPLAY_INDEX = FADER_PARAMETER_DISPLAY_START_INDEX + 8
